'use client';
import {useEffect,useState,useRef} from 'react';
import ReservationCalendar from './reservation-calendar';
type Choice={time:string;serviceId:string;startsAt:string;available:boolean;remaining:number};
export const labels:Record<string,string>={pending:'En attente',confirmed:'Confirmée',arrived:'Arrivée',completed:'Terminée',cancelled:'Annulée',no_show:'Absence',interior:'Intérieur',terrace:'Terrasse',phone:'Téléphone',email:'Email',instagram:'Instagram',facebook:'Facebook',site:'Site'};
export const parisDay=(d=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
export const parisTime=(s:string)=>new Intl.DateTimeFormat('fr-FR',{timeZone:'Europe/Paris',hour:'2-digit',minute:'2-digit'}).format(new Date(s));
export default function ConnectedBooking({admin=false,edit,onSaved}:{admin?:boolean;edit?:any;onSaved?:()=>void}){
 const requestKey=useRef('');
 useEffect(()=>{requestKey.current=crypto.randomUUID();},[]);
 const [date,setDate]=useState(edit?.date||''),[people,setPeople]=useState(edit?.people||2),[preference,setPreference]=useState(edit?.preference||'interior'),[time,setTime]=useState(edit?parisTime(edit.starts_at):''),[choices,setChoices]=useState<Choice[]>([]),[closed,setClosed]=useState<string[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<{token:string;status:string}|null>(null);
 useEffect(()=>{if(!date)setDate(parisDay());},[date]);
 useEffect(()=>{if(!date)return;const controller=new AbortController();setLoading(true);setError('');fetch('/api/availability?'+new URLSearchParams({date,people:String(people),preference}),{cache:'no-store',signal:controller.signal}).then(async res=>{const data=await res.json();if(!res.ok)throw Error(data.error);setChoices(data.choices);setClosed(data.closedDates);}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setChoices([]);}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[date,people,preference]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const fields=Object.fromEntries(new FormData(e.currentTarget));const choice=choices.find(c=>c.time===time);if(!requestKey.current)requestKey.current=crypto.randomUUID();try{if(!choice)throw Error('Choisissez un créneau.');const res=await fetch(admin?'/api/gerant/reservations':'/api/reservations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,requestKey:requestKey.current,serviceId:choice.serviceId,startsAt:choice.startsAt,people,preference,...(admin?{action:edit?'update':'add',id:edit?.id,revision:edit?.revision,status:edit?.status}: {})})});const data=await res.json();if(!res.ok)throw Error(data.error);if(admin){onSaved?.();}else setReceipt(data);}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible.');}finally{setBusy(false);}}
 if(receipt)return <div role="status"><h3>{labels[receipt.status]} · essai enregistré</h3><p>La réservation est enregistrée dans la base de test commune. Aucun message envoyé.</p><a className="button" href={'/reservation#'+receipt.token}>Consulter ou modifier cet essai ↗</a><p className="small">Conservez ce lien privé : il permet de gérer votre réservation.</p><button className="text-link" onClick={()=>{requestKey.current=crypto.randomUUID();setReceipt(null);setTime('');}}>Faire un autre essai</button></div>;
 return <form className="booking-form" onChange={()=>{requestKey.current=crypto.randomUUID();}} onSubmit={submit}><p className="warning">ESSAI CONNECTÉ · Coordonnées fictives uniquement. 100 couverts par service ; durée prévue provisoire : 2 heures. Aucun SMS envoyé.</p><div className="field-grid"><ReservationCalendar value={date} min={parisDay()} closures={[]} closedDates={closed} onChange={d=>{setDate(d);setTime('');}}/><label>Personnes<select value={people} onChange={e=>{setPeople(+e.target.value);setTime('');}}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label></div><fieldset><legend>Préférence de placement</legend><div className="segmented">{['interior','terrace'].map(p=><button type="button" key={p} aria-pressed={preference===p} className={preference===p?'selected':''} onClick={()=>{setPreference(p);setTime('');}}>{labels[p]}</button>)}</div><p className="small muted">La préférence ne garantit pas votre placement. Les gérants organisent les tables.</p></fieldset><fieldset><legend>Créneaux de la base commune</legend>{loading?<p role="status">Recherche des disponibilités…</p>:<div className="slots">{choices.map(c=><button type="button" key={c.time} disabled={!c.available&&!(edit&&c.serviceId===edit.service_id&&c.remaining+edit.people>=people)} className={time===c.time?'selected':''} aria-pressed={time===c.time} onClick={()=>setTime(c.time)}>{c.time}</button>)}</div>}{!loading&&!choices.some(c=>c.available)&&!edit&&<p>Aucun créneau disponible pour cette sélection.</p>}</fieldset><label>Nom<input name="name" required minLength={2} maxLength={80} defaultValue={edit?.name} placeholder="Nom fictif pour le test" autoComplete="off"/></label><div className="field-grid"><label>Téléphone<input name="phone" required type="tel" pattern="[+0-9 ()-]{8,20}" defaultValue={edit?.phone} placeholder="Numéro fictif"/></label><label>Email<input name="email" required type="email" defaultValue={edit?.email} placeholder="exemple@example.com"/></label></div><label>Une attention particulière ?<textarea name="comment" maxLength={500} rows={2} defaultValue={edit?.comment}/></label><label>Allergies et besoins alimentaires<textarea name="allergies" maxLength={300} rows={2} defaultValue={edit?.allergies} placeholder="Sans gluten, allergie aux arachides…"/><span className="small muted">L’équipe doit confirmer les adaptations possibles.</span></label>{admin&&!edit&&<label>Source<select name="source" defaultValue="phone">{['phone','email','instagram','facebook','site'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>}{error&&<p role="alert" className="warning">{error}</p>}<button className="button" disabled={busy||loading||!time}>{busy?'Enregistrement…':edit?'Enregistrer les modifications':admin?'Ajouter à la base de test':'Réserver · essai connecté'} ↗</button></form>;
}
