import {configured,authenticated} from '../../lib/server/auth';
import {db} from '../../lib/server/db';
export const dynamic='force-dynamic';
export default async function Page({searchParams}:{searchParams:Promise<{erreur?:string}>}){
 if(!configured())return <main className="admin"><p className="eyebrow">LA TOUR DE MONTADY</p><h1>Accès privé non configuré.</h1><p>L’authentification et la connexion aux données réelles doivent être activées avant la mise en service. Cette page ne donne accès à aucune réservation.</p><a className="text-link" href="/demo/gerant">Explorer l’interface de démonstration →</a></main>;
 if(!await authenticated())return <main className="admin admin-form"><p className="eyebrow">LA TOUR DE MONTADY · ACCÈS GÉRANT</p><h1>Votre espace privé.</h1><p>Connectez-vous pour accéder aux données de la base de test.</p>{(await searchParams).erreur&&<p role="alert" className="warning">Connexion refusée. Vérifiez vos identifiants ou réessayez plus tard.</p>}<form action="/api/gerant/login" method="post"><label>Email<input name="email" type="email" required maxLength={254} autoComplete="username"/></label><label>Mot de passe<input name="password" type="password" required maxLength={200} autoComplete="current-password"/></label><button className="button">Se connecter →</button></form><a className="text-link" href="/">Retour au restaurant →</a></main>;
 const rows=await db()`SELECT id,name,people,starts_at,status,zone,source FROM reservations WHERE starts_at>now()-interval '24 hours' ORDER BY starts_at LIMIT 200`;
 return <main className="admin"><div className="admin-heading"><div><p className="eyebrow">BASE DE TEST · ACCÈS AUTHENTIFIÉ</p><h1>Les réservations.</h1></div><form action="/api/gerant/logout" method="post"><button>Se déconnecter</button></form></div><p className="warning">Base de test connectée. Le formulaire public reste en démonstration et aucun SMS n’est envoyé. Les réservations enregistrées dans votre navigateur ne sont pas importées ici.</p><p>La consultation utilise la base commune. Les actions de gestion et le formulaire seront raccordés à la prochaine étape.</p>{!rows.length&&<div className="empty"><h2>Aucune réservation dans la base.</h2><p>La connexion est prête pour les prochains essais.</p></div>}{rows.map(r=><article className="reservation-row" key={r.id}><strong>{r.name}</strong><span>{r.people} personnes · {new Date(r.starts_at).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})}</span><span>{r.zone} · {r.status} · {r.source}</span></article>)}</main>;
}
