import {authenticated,allowedOrigin} from '../../../../lib/server/auth';
import {db,assertConnected} from '../../../../lib/server/db';
import {ensureServices,today} from '../../../../lib/server/services';
import {reserve,bookingInput} from '../../../../lib/server/reservations';
import {modify,updateInput} from '../../../../lib/server/manage';
import {z} from 'zod';
export const runtime='nodejs';
export async function GET(request:Request){try{if(!await authenticated())return Response.json({error:'Connexion requise.'},{status:401});assertConnected();const date=new URL(request.url).searchParams.get('date')||'';if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('INVALID');if(date>=today())await ensureServices(date);const bookings=await db()`SELECT r.id,r.service_id,r.starts_at,r.ends_at,r.people,r.preference,r.zone,r.status,r.name,r.phone,r.email,r.comment,r.allergies,r.source,r.revision,s.date::text AS date FROM reservations r JOIN services s ON s.id=r.service_id WHERE s.date=${date} ORDER BY starts_at,created_at`;const services=await db()`SELECT * FROM services WHERE date=${date} ORDER BY first_arrival`;const logs=await db()`SELECT at,event,actor FROM audit_events ORDER BY at DESC LIMIT 40`;return Response.json({bookings,services,logs},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Données indisponibles.'},{status:503});}}
export async function POST(request:Request){if(!allowedOrigin(request))return Response.json({error:'Origine refusée.'},{status:403});try{if(!await authenticated())return Response.json({error:'Connexion requise.'},{status:401});assertConnected();const body=await request.json();if(body.action==='add'){const source=z.enum(['phone','email','instagram','facebook','site']).parse(body.source);const result=await reserve(bookingInput.parse(body),''+source,'admin',body.requestKey);return Response.json({id:result.id,status:result.status},{status:201});}if(body.action==='update')return Response.json(await modify(updateInput.parse(body)));if(body.action==='closure'){const input=z.object({serviceId:z.uuid(),closed:z.boolean()}).parse(body);await db().begin(async tx=>{const [s]=await tx`SELECT id FROM services WHERE id=${input.serviceId} FOR UPDATE`;if(!s)throw Error('NOT_FOUND');await tx`UPDATE services SET closed=${input.closed} WHERE id=${input.serviceId}`;await tx`INSERT INTO audit_events(actor,event,details) VALUES('admin','service_closure',${tx.json(input)})`;});return Response.json({ok:true});}throw Error('INVALID');}catch(e){return Response.json({error:e instanceof Error&&['CONFLICT','UNAVAILABLE'].includes(e.message)?'Ce créneau ou cette réservation a changé. Actualisez puis réessayez.':'Action impossible. Aucun changement enregistré.'},{status:409});}}
